version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"

    working_directory: /go/go-exercism
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
